# Site settings
title: Cloudscaling
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cloudscaling is the leading provider of on-premise elastic cloud infrastructure solutions to support dynamic applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stage.www.cloudscaling.com.s3-website-us-west-2.amazonaws.com" # the base hostname & protocol for your site
twitter_username: randybias
github_username:  randybias

# Build settings
markdown: kramdown
